title:              SaySam's Blog
email:              realhistory8282@gmail.com
description:        M.S. student in Information and Communication Engineering @ Tsinghua University.
author:             Sam Lee
baseurl:            ""
url:                "https://saysam1252.github.io"

# Social Profiles
twitter_username:   
github_username:    SaySam1252
facebook_username:  
instagram_username: ssang_x2 
linkedin_username: eunsang-lee

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
